# Generated by Django 5.2 on 2025-04-15 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='document_verification_status',
            field=models.CharField(choices=[('not_submitted', 'Not Submitted'), ('pending', 'Pending Verification'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='not_submitted', help_text='Status of document verification for this property', max_length=20),
        ),
        migrations.CreateModel(
            name='PropertyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('deed', 'Property Deed'), ('tax', 'Property Tax Document'), ('utility', 'Utility Bill'), ('insurance', 'Property Insurance'), ('id', 'ID Card with Address'), ('other', 'Other Document')], default='other', max_length=20)),
                ('document', models.FileField(upload_to='property_documents/')),
                ('description', models.TextField(blank=True, help_text='Additional information about the document', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection if applicable', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='properties.property')),
            ],
            options={
                'verbose_name': 'Property Document',
                'verbose_name_plural': 'Property Documents',
                'ordering': ['-created_at'],
            },
        ),
    ]
