# Generated by Django 5.2 on 2025-04-15 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_property_document_verification_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='document_verification_status',
            field=models.CharField(blank=True, choices=[('not_submitted', 'Not Submitted'), ('pending', 'Pending Verification'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='not_submitted', help_text='Status of document verification for this property', max_length=20, null=True),
        ),
    ]
