# Generated by Django 5.2 on 2025-04-15 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_alter_property_document_verification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertydocument',
            name='feedback',
            field=models.TextField(blank=True, help_text='Feedback for the document owner without changing status', null=True),
        ),
    ]
