# Generated by Django 5.2 on 2025-04-15 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_propertydocument_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertydocument',
            name='feedback_read',
            field=models.BooleanField(default=False, help_text='Whether the feedback has been read by the owner'),
        ),
    ]
