# Generated by Django 5.2 on 2025-04-15 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_propertydocument_feedback_read'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('admin', 'Admin'), ('landlord', 'Landlord')], help_text='Type of user who sent this feedback', max_length=10)),
                ('message', models.TextField(help_text='Feedback message')),
                ('is_read', models.BooleanField(default=False, help_text='Whether this feedback has been read by the recipient')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_thread', to='properties.propertydocument')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document Feedback',
                'verbose_name_plural': 'Document Feedback',
                'ordering': ['created_at'],
            },
        ),
    ]
