# Generated by Django 5.2 on 2025-05-26 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_documentfeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='address',
            field=models.CharField(help_text='Google Autocomplete Address', max_length=255),
        ),
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.CharField(help_text='Google Autocomplete City', max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='country',
            field=models.CharField(default='Rwanda', help_text='Google Autocomplete Country, always Rwanda', max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Google Autocomplete Latitude', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Google Autocomplete Longitude', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='state',
            field=models.CharField(help_text='Google Autocomplete State', max_length=100),
        ),
    ]
